const langData = {
    en: {
        darkMode: "Dark Mode",
        brightMode: "Bright Mode",
        welcome: "Welcome to the website of Soumyabrata Bhattacharjee",
        personalDetails: "Personal details",
        name: "Name: Soumyabrata Bhattacharjee",
        father: "Father: Rajesh Bhattacharjee",
        mother: "Mother: Papiya Bhattacharya",
        address: "Address: Natunpally, Ward 8, P.O. Burdwan",
        district: "District: Purba Bardhaman",
        pin: "Pin: 713101",
        state: "State: West Bengal",
        dateOfBirth: "Date of Birth: 27 May 2006",
        qualifications: "Academic qualifications",
        degree: "Degree",
        institution: "Institution",
        parentInstitution: "Parent institution",
        grade: "Grade",
        btech: "Bachelor of Technology in Computer Science and Engineering (pursuing)",
        aot: "Academy of Technology",
        makaut: "Maulana Abul Kalam Azad University of Technology",
        cgpa: "CGPA: 8.05",
        higherSecondary: "Higher Secondary",
        school: "Burdwan Town School",
        wbchse: "West Bengal Council of Higher Secondary Education",
        hsPercent: "87%",
        madhyamik: "Madhyamik",
        wbbse: "West Bengal Board of Secondary Education",
        mpPercent: "88%",
        expertise: "Areas of Expertise",
        webDev: "Web development: HTML, CSS, JavaScript",
        softDev: "Software development: C, C++, Python",
        graphics: "Graphics: FreeCAD, Inkscape",
        os: "Operating systems: Windows 11, Windows Subsystems for Linux",
        others: "Other software: VS Code, Notepad++, GCC, Microsoft Office",
        hobbies: "Hobbies: Photography, Travel",
        contact: "Contact me",
        personalEmail: "Personal email:",
        academicEmail: "Academic email:",
        phone: "Phone number:",
        websites: "Websites",
        fb: "Facebook",
        gh: "GitHub",
        li: "LinkedIn",
        ex: "X"
    },
    bn: {
        darkMode: "আঁধার মোড",
        brightMode: "উজ্জ্বল মোড",
        welcome: "সৌম্যব্রত ভট্টাচার্য্যের ওয়েবসাইটে আপনাকে স্বাগতম",
        personalDetails: "ব্যক্তিগত বিবরণ",
        name: "নাম: সৌম্যব্রত ভট্টাচার্য্য",
        father: "পিতা: রাজেশ ভট্টাচার্য্য",
        mother: "মাতা: পাপিয়া ভট্টাচার্য্য",
        address: "ঠিকানা: নতুনপল্লী, ওয়ার্ড নং ৮, পো. বর্ধমান",
        district: "জেলা: পূর্ব বর্ধমান",
        pin: "পিন: ৭১৩১০১",
        state: "রাজ্য: পশ্চিমবঙ্গ",
        dateOfBirth: "জন্মতারিখ: ২৭ মে ২০০৬",
        qualifications: "শিক্ষাগত যোগ্যতা",
        degree: "ডিগ্রি",
        institution: "প্রতিষ্ঠান",
        parentInstitution: "উচ্চতর প্রতিষ্ঠান",
        grade: "গ্রেড",
        btech: "ব্যাচেলর অব টেকনোলজি, কম্পিউটার সায়েন্স অ্যান্ড ইঞ্জিনিয়ারিং (স্নাতক শ্রেণী)",
        aot: "অ্যাকাডেমি অব টেকনোলজি",
        makaut: "মৌলানা আবুল কালাম আজাদ প্রযুক্তি বিশ্ববিদ্যালয়",
        cgpa: "সিজিপিএ: ৮.০৫",
        higherSecondary: "উচ্চ মাধ্যমিক",
        school: "বর্ধমান টাউন স্কুল",
        wbchse: "পশ্চিমবঙ্গ উচ্চ মাধ্যমিক শিক্ষা সংসদ",
        hsPercent: "৮৭%",
        madhyamik: "মাধ্যমিক",
        wbbse: "পশ্চিমবঙ্গ মাধ্যমিক শিক্ষা পর্ষদ",
        mpPercent: "৮৮%",
        expertise: "বিশেষ জ্ঞান ও দক্ষতা",
        webDev: "ওয়েব ডেভেলপমেন্ট: এইচটিএমএল, সিএসএস, জাভাস্ক্রিপ্ট",
        softDev: "সফটওয়্যার ডেভেলপমেন্ট: সি, সি++, পাইথন",
        graphics: "গ্রাফিক্স: ফ্রিক্যাড, ইঙ্কস্কেপ",
        os: "অপারেটিং সিস্টেম: উইন্ডোজ ১১, উইন্ডোজ সাবসিস্টেমস ফর লিনাক্স",
        others: "অন্যান্য সফটওয়্যার: ভিএস কোড, নোটপ্যাড++, জিসিসি, মাইক্রোসফ্ট অফিস",
        hobbies: "শখ: ফটোগ্রাফি, ভ্রমণ",
        contact: "যোগাযোগ করুন",
        personalEmail: "ব্যক্তিগত ইমেল:",
        academicEmail: "অ্যাকাডেমিক ইমেল:",
        phone: "ফোন নম্বর:",
        websites: "ওয়েবসাইট",
        fb: "ফেসবুক",
        gh: "গিটহাব",
        li: "লিঙ্কডইন",
        ex: "এক্স"
    },
    hi: {
        darkMode: "गहरा मोड",
        brightMode: "दिन मोड",
        welcome: "सौम्यव्रत भट्टाचार्य का वेबसाइट पर आपका स्वागत है",
        personalDetails: "व्यक्ति परिचय",
        name: "नाम: सौम्यव्रत भट्टाचार्य",
        father: "पिता: राजेश भट्टाचार्य",
        mother: "माता: पापिया भट्टाचार्य",
        address: "ठिकाना: नतुनपल्ली, वर्ड नं ८, पो. बर्धमान",
        district: "ज़िला: पूर्व बर्धमान",
        pin: "पिन: ७१३१०१",
        state: "राज्य: पश्चिम बंगाल",
        dateOfBirth: "जन्म तारीख: १७ मई २००६",
        qualifications: "शिक्षा योग्यता",
        degree: "डिग्री",
        institution: "संस्थान",
        parentInstitution: "मालिक संस्थान",
        grade: "ग्रेड",
        btech: "बैच्लर ऑफ़ टेक्नॉलजी, कंप्युटर साइंस एण्ड इंजीनियरिंग (अंडर ग्रैजूइट)",
        aot: "एकडेमी ऑफ़ टेक्नॉलजी",
        makaut: "मौलाना अबुल कलाम आज़ाद प्रद्योगिकी विश्वविद्यालय",
        cgpa: "सीजीपीए: ८.०५",
        higherSecondary: "उच्च माध्यमिक",
        school: "बर्धमान टाउन स्कूल",
        wbchse: "पश्चिम बंगाल उच्च माध्यमिक शिक्षा संसद",
        hsPercent: "८७%",
        madhyamik: "माध्यमिक",
        wbbse: "पश्चिम बंगाल माध्यमिक शिक्षा पर्षद",
        mpPercent: "८८%",
        expertise: "विशेषज्ञता",
        webDev: "वेब डेवेलोपमेंट: एचटीएमएल, सीएसएस, जावास्क्रिप्ट",
        softDev: "सॉफ़्टवेयर डेवेलोपमेंट: सी, सी++, पाइथॉन",
        graphics: "ग्राफ़िक्स: फ्रीकैड, इंकस्केप",
        os: "ऑपरेटिंग सीस्टम: विंडोज़ ११, विंडोज़ सबसिस्टम्स फ़ॉर लिनक्स",
        others: "अन्य सॉफ़्टवेयर: वीएस कोड, नोटपैड++, जीसीसी, माइक्रोसॉफ़्ट ऑफ़िस",
        hobbies: "मनोविनोद: फ़ोटोग्राफ़ी, यात्रा",
        contact: "संपर्क करें",
        personalEmail: "व्यक्ति ईमेल:",
        academicEmail: "एकडेमिक ईमेल:",
        phone: "फ़ोन नंबर:",
        websites: "वेबसाइट",
        fb: "फ़ेसबुक",
        gh: "गिटहब",
        li: "लिंक्डइन",
        ex: "एक्स"
    }
}